--PSFFS_READ Role
--Create the role
create role PSFFS_READ not identified;

--Assign grants to the role
--GEN STATEMENT: SELECT 'grant SELECT on "PSFFS"."' || TABLE_NAME || '" to PSFFS_READ;' FROM user_tables;
--GEN STATEMENT: SELECT 'grant SELECT on "PSFFS"."' || SEQUENCE_NAME || '" to PSFFS_READ;' FROM user_sequences;
--Tables
grant SELECT on "PSFFS"."PSFFS_USER_ROLE" to PSFFS_READ;
grant SELECT on "PSFFS"."CTAB_UNIT_AREA" to PSFFS_READ;
grant SELECT on "PSFFS"."CTAB_NAFO_DIVISION" to PSFFS_READ;
grant SELECT on "PSFFS"."CTAB_GEAR" to PSFFS_READ;
grant SELECT on "PSFFS"."CTAB_OBSERVER_COMPANY" to PSFFS_READ;
grant SELECT on "PSFFS"."PSFFS_OPERATIONAL_CODE" to PSFFS_READ;
grant SELECT on "PSFFS"."PSFFS_ROLE" to PSFFS_READ;
grant SELECT on "PSFFS"."PSFFS_USER_PREFERENCE" to PSFFS_READ;
grant SELECT on "PSFFS"."CTAB_PORT" to PSFFS_READ;
grant SELECT on "PSFFS"."PSFFS_USER" to PSFFS_READ;
grant SELECT on "PSFFS"."CTAB_TONNAGE" to PSFFS_READ;
grant SELECT on "PSFFS"."CTAB_QUOTA" to PSFFS_READ;
grant SELECT on "PSFFS"."CTAB_CATCH_CATEGORY" to PSFFS_READ;
grant SELECT on "PSFFS"."CTAB_OTOLITH_EDGE" to PSFFS_READ;
grant SELECT on "PSFFS"."CTAB_STOMACH_CONTENT" to PSFFS_READ;
grant SELECT on "PSFFS"."CTAB_PARASITE" to PSFFS_READ;
grant SELECT on "PSFFS"."CTAB_MEASURING_TECHNIQUE" to PSFFS_READ;
grant SELECT on "PSFFS"."CTAB_DATA_SOURCE" to PSFFS_READ;
grant SELECT on "PSFFS"."CTAB_LENGTH_CATEGORY" to PSFFS_READ;
grant SELECT on "PSFFS"."CTAB_LENGTH_GROUP" to PSFFS_READ;
grant SELECT on "PSFFS"."CTAB_VESSEL" to PSFFS_READ;
grant SELECT on "PSFFS"."CTAB_SPECIES" to PSFFS_READ;
grant SELECT on "PSFFS"."CTAB_WGHT_CONV_FACTOR" to PSFFS_READ;
grant SELECT on "PSFFS"."WGHT_CONV_FCTR_SPECIES" to PSFFS_READ;
grant SELECT on "PSFFS"."CTAB_QUARTER" to PSFFS_READ;
grant SELECT on "PSFFS"."CTAB_MATURITY" to PSFFS_READ;
grant SELECT on "PSFFS"."PSFFS_SYS_SETTING" to PSFFS_READ;
grant SELECT on "PSFFS"."SAMPLING_SETTING" to PSFFS_READ;
grant SELECT on "PSFFS"."CELL_DEFINITION" to PSFFS_READ;
grant SELECT on "PSFFS"."SAMPLING_CELL" to PSFFS_READ;
grant SELECT on "PSFFS"."SAMPLING" to PSFFS_READ;
grant SELECT on "PSFFS"."SMPLNG_LENGTH_FREQUENCY" to PSFFS_READ;
grant SELECT on "PSFFS"."SMPLNG_TRIP_SET_SPECIES" to PSFFS_READ;
grant SELECT on "PSFFS"."SAMPLING_DATA" to PSFFS_READ;
grant SELECT on "PSFFS"."SAMPLING_ENTRY" to PSFFS_READ;
grant SELECT on "PSFFS"."SMPLNG_LENGTH_FREQUENCY_COUNT" to PSFFS_READ;
grant SELECT on "PSFFS"."CTAB_CONDITION_LANDED" to PSFFS_READ;
grant SELECT on "PSFFS"."PSFFS_CHECKSUM_FOR_OBJECT" to PSFFS_READ;
grant SELECT on "PSFFS"."PSFFS_EXTRACT" to PSFFS_READ;
grant SELECT on "PSFFS"."SAMPLING_IDENT_GEN" to PSFFS_READ;
--Sequences
grant SELECT on "PSFFS"."CELL_DEFINITION_ID_SEQ" to PSFFS_READ;
grant SELECT on "PSFFS"."CTAB_CATCH_CATEGORY_ID_SEQ" to PSFFS_READ;
grant SELECT on "PSFFS"."CTAB_CONDITION_LANDED_ID_SEQ" to PSFFS_READ;
grant SELECT on "PSFFS"."CTAB_DATA_SOURCE_ID_SEQ" to PSFFS_READ;
grant SELECT on "PSFFS"."CTAB_GEAR_ID_SEQ" to PSFFS_READ;
grant SELECT on "PSFFS"."CTAB_LENGTH_CATEGORY_ID_SEQ" to PSFFS_READ;
grant SELECT on "PSFFS"."CTAB_LENGTH_GROUP_ID_SEQ" to PSFFS_READ;
grant SELECT on "PSFFS"."CTAB_MATURITY_ID_SEQ" to PSFFS_READ;
grant SELECT on "PSFFS"."CTAB_MEASURING_TECH_ID_SEQ" to PSFFS_READ;
grant SELECT on "PSFFS"."CTAB_NAFO_DIVISION_ID_SEQ" to PSFFS_READ;
grant SELECT on "PSFFS"."CTAB_OBSERVER_COMPANY_ID_SEQ" to PSFFS_READ;
grant SELECT on "PSFFS"."CTAB_OTOLITH_EDGE_ID_SEQ" to PSFFS_READ;
grant SELECT on "PSFFS"."CTAB_PARASITE_ID_SEQ" to PSFFS_READ;
grant SELECT on "PSFFS"."CTAB_PORT_ID_SEQ" to PSFFS_READ;
grant SELECT on "PSFFS"."CTAB_QUARTER_ID_SEQ" to PSFFS_READ;
grant SELECT on "PSFFS"."CTAB_QUOTA_ID_SEQ" to PSFFS_READ;
grant SELECT on "PSFFS"."CTAB_SPECIES_ID_SEQ" to PSFFS_READ;
grant SELECT on "PSFFS"."CTAB_STOMACH_CONTENT_ID_SEQ" to PSFFS_READ;
grant SELECT on "PSFFS"."CTAB_TONNAGE_ID_SEQ" to PSFFS_READ;
grant SELECT on "PSFFS"."CTAB_UNIT_AREA_ID_SEQ" to PSFFS_READ;
grant SELECT on "PSFFS"."CTAB_VESSEL_ID_SEQ" to PSFFS_READ;
grant SELECT on "PSFFS"."CTAB_WGHT_CONV_FACTOR_ID_SEQ" to PSFFS_READ;
grant SELECT on "PSFFS"."PSFFS_CHKSUM_FOR_OBJECT_ID_SEQ" to PSFFS_READ;
grant SELECT on "PSFFS"."PSFFS_EXTRACT_ID_SEQ" to PSFFS_READ;
grant SELECT on "PSFFS"."PSFFS_USER_ID_SEQ" to PSFFS_READ;
grant SELECT on "PSFFS"."PSFFS_USER_PREFERENCE_ID_SEQ" to PSFFS_READ;
grant SELECT on "PSFFS"."PSFFS_USER_ROLE_ID_SEQ" to PSFFS_READ;
grant SELECT on "PSFFS"."SAMPLING_CELL_ID_SEQ" to PSFFS_READ;
grant SELECT on "PSFFS"."SAMPLING_DATA_ID_SEQ" to PSFFS_READ;
grant SELECT on "PSFFS"."SAMPLING_ENTRY_ID_SEQ" to PSFFS_READ;
grant SELECT on "PSFFS"."SAMPLING_IDENT_GEN_ID_SEQ" to PSFFS_READ;
grant SELECT on "PSFFS"."SAMPLING_ID_SEQ" to PSFFS_READ;
grant SELECT on "PSFFS"."SAMPLING_SETTING_ID_SEQ" to PSFFS_READ;
grant SELECT on "PSFFS"."SMPLNG_LENGTH_FREQUENCY_ID_SEQ" to PSFFS_READ;
grant SELECT on "PSFFS"."SMPLNG_LENGTH_FREQ_CNT_ID_SEQ" to PSFFS_READ;
grant SELECT on "PSFFS"."SMPLNG_TRIP_SET_SPECIES_ID_SEQ" to PSFFS_READ;

--PSFFS_UPDATE Role
--Create the role
create role PSFFS_UPDATE not identified;

--Assign grants to the role
--GEN STATEMENT: SELECT 'grant UPDATE, INSERT, DELETE on "PSFFS"."' || TABLE_NAME || '" to PSFFS_UPDATE;' FROM user_tables;
grant UPDATE, INSERT, DELETE on "PSFFS"."PSFFS_USER_ROLE" to PSFFS_UPDATE;
grant UPDATE, INSERT, DELETE on "PSFFS"."CTAB_UNIT_AREA" to PSFFS_UPDATE;
grant UPDATE, INSERT, DELETE on "PSFFS"."CTAB_NAFO_DIVISION" to PSFFS_UPDATE;
grant UPDATE, INSERT, DELETE on "PSFFS"."CTAB_GEAR" to PSFFS_UPDATE;
grant UPDATE, INSERT, DELETE on "PSFFS"."CTAB_OBSERVER_COMPANY" to PSFFS_UPDATE;
grant UPDATE, INSERT, DELETE on "PSFFS"."PSFFS_OPERATIONAL_CODE" to PSFFS_UPDATE;
grant UPDATE, INSERT, DELETE on "PSFFS"."PSFFS_ROLE" to PSFFS_UPDATE;
grant UPDATE, INSERT, DELETE on "PSFFS"."PSFFS_USER_PREFERENCE" to PSFFS_UPDATE;
grant UPDATE, INSERT, DELETE on "PSFFS"."CTAB_PORT" to PSFFS_UPDATE;
grant UPDATE, INSERT, DELETE on "PSFFS"."PSFFS_USER" to PSFFS_UPDATE;
grant UPDATE, INSERT, DELETE on "PSFFS"."CTAB_TONNAGE" to PSFFS_UPDATE;
grant UPDATE, INSERT, DELETE on "PSFFS"."CTAB_QUOTA" to PSFFS_UPDATE;
grant UPDATE, INSERT, DELETE on "PSFFS"."CTAB_CATCH_CATEGORY" to PSFFS_UPDATE;
grant UPDATE, INSERT, DELETE on "PSFFS"."CTAB_OTOLITH_EDGE" to PSFFS_UPDATE;
grant UPDATE, INSERT, DELETE on "PSFFS"."CTAB_STOMACH_CONTENT" to PSFFS_UPDATE;
grant UPDATE, INSERT, DELETE on "PSFFS"."CTAB_PARASITE" to PSFFS_UPDATE;
grant UPDATE, INSERT, DELETE on "PSFFS"."CTAB_MEASURING_TECHNIQUE" to PSFFS_UPDATE;
grant UPDATE, INSERT, DELETE on "PSFFS"."CTAB_DATA_SOURCE" to PSFFS_UPDATE;
grant UPDATE, INSERT, DELETE on "PSFFS"."CTAB_LENGTH_CATEGORY" to PSFFS_UPDATE;
grant UPDATE, INSERT, DELETE on "PSFFS"."CTAB_LENGTH_GROUP" to PSFFS_UPDATE;
grant UPDATE, INSERT, DELETE on "PSFFS"."CTAB_VESSEL" to PSFFS_UPDATE;
grant UPDATE, INSERT, DELETE on "PSFFS"."CTAB_SPECIES" to PSFFS_UPDATE;
grant UPDATE, INSERT, DELETE on "PSFFS"."CTAB_WGHT_CONV_FACTOR" to PSFFS_UPDATE;
grant UPDATE, INSERT, DELETE on "PSFFS"."WGHT_CONV_FCTR_SPECIES" to PSFFS_UPDATE;
grant UPDATE, INSERT, DELETE on "PSFFS"."CTAB_QUARTER" to PSFFS_UPDATE;
grant UPDATE, INSERT, DELETE on "PSFFS"."CTAB_MATURITY" to PSFFS_UPDATE;
grant UPDATE, INSERT, DELETE on "PSFFS"."PSFFS_SYS_SETTING" to PSFFS_UPDATE;
grant UPDATE, INSERT, DELETE on "PSFFS"."SAMPLING_SETTING" to PSFFS_UPDATE;
grant UPDATE, INSERT, DELETE on "PSFFS"."CELL_DEFINITION" to PSFFS_UPDATE;
grant UPDATE, INSERT, DELETE on "PSFFS"."SAMPLING_CELL" to PSFFS_UPDATE;
grant UPDATE, INSERT, DELETE on "PSFFS"."SAMPLING" to PSFFS_UPDATE;
grant UPDATE, INSERT, DELETE on "PSFFS"."SMPLNG_LENGTH_FREQUENCY" to PSFFS_UPDATE;
grant UPDATE, INSERT, DELETE on "PSFFS"."SMPLNG_TRIP_SET_SPECIES" to PSFFS_UPDATE;
grant UPDATE, INSERT, DELETE on "PSFFS"."SAMPLING_DATA" to PSFFS_UPDATE;
grant UPDATE, INSERT, DELETE on "PSFFS"."SAMPLING_ENTRY" to PSFFS_UPDATE;
grant UPDATE, INSERT, DELETE on "PSFFS"."SMPLNG_LENGTH_FREQUENCY_COUNT" to PSFFS_UPDATE;
grant UPDATE, INSERT, DELETE on "PSFFS"."CTAB_CONDITION_LANDED" to PSFFS_UPDATE;
grant UPDATE, INSERT, DELETE on "PSFFS"."PSFFS_CHECKSUM_FOR_OBJECT" to PSFFS_UPDATE;
grant UPDATE, INSERT, DELETE on "PSFFS"."PSFFS_EXTRACT" to PSFFS_UPDATE;
grant UPDATE, INSERT, DELETE on "PSFFS"."SAMPLING_IDENT_GEN" to PSFFS_UPDATE;

--Assign the PSFFS_READ and PSFFS_UPDATE roles to PSFFS_WEB_USER
--grant PSFFS_READ to PSFFS_WEB_USER;
--grant PSFFS_UPDATE to PSFFS_WEB_USER;